# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d106360915b873bb987743e0465870b3b4a4e82451754f3a66bb75e6a384e049ff141454d105b3e4bcb449452276b1754a0b036520cde3baa9789feaf2f74d

test:
  secret_key_base: 2b6161b686884245ae527bce2074d51137e0d77a462e5de043d10f09dbaba60780bdb124b117eec63d2a224ece72e5f6699f49e48c3b21a282b3b512d11a0824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
